### ISSUE TITLE
Display resource being played to chat

### ISSUE THREAD

**Issue by itniels** [jack3898/discord-yt-bot#27]
## Description
It would be really nice to see the URL that was played (maybe even with metadata like song name/image) in the chat, often using this for a work channel where it would be cool to go back and find songs played previously and copy the resource.

This is low priority, and if I get some time I might try and give it a stab myself, but pretty swamped currently 😅 

Here is where the text should include the video being played:
![image](https://user-images.githubusercontent.com/15611687/229902119-4a895112-cc9b-4b37-b427-8889ace9579b.png)

**Comment by jack3898** [comment]
Ah yes oops I may have removed that in the recent update 😬, I'll work on it!

While I'm at it I'll make it a nice embed with video statistics like channel name, views, URL etc. 😁👍

**Comment by jack3898** [comment]
Hey itneils, I added it as requested! Latest changed on linked branch.

![image](https://user-images.githubusercontent.com/28375223/232313843-092b384f-0194-4f4a-aa70-aaace49a8bc1.png)

Let me know if there is anything you could improve. I will merge later this evening, but if you can't respond by then I can always spin up a new branch!

It does not yet work with /play, because I think that needs more thought as it runs through a queue (and could be easy to mess up).

**Comment by jack3898** [comment]
Quick update, I added the channel name and uploaded date to the embed footer:

![image](https://user-images.githubusercontent.com/28375223/232314783-bde06128-a634-4f48-b723-b8f40dd5e774.png)

The date time format can be changed to respect your locale in the langpacks file.
apps\bot\src\langpacks\en_gb.ts

Just change `LOCALE` to yours if you're not happy with the date format 🤣

**Comment by itniels** [comment]
Awesome :) Can't wait to try it @jack3898 

We mainly just use `/quickplay` 99% of the time, it would just be awesome to have a quick way of getting the url for previous played videos in the chat for easy copy/paste replay 🙂

**Comment by jack3898** [comment]
Yep I merged it (I got hasty 🤣) so pull main and hopefully it works well enough for you! Seems to have everything you asked for I hope!

**Comment by itniels** [comment]
Thanks @jack3898 🙂 
Will take it for a spin tomorrow
